// The coin ledger, in Postgres, as the record of truth.
//
// SQLite's coin_ledger (migration 007) still exists and still gets every row —
// it is what keeps the game playable with no DATABASE_URL, and it is the local
// record. But when Postgres is configured, *this* is the ledger that counts:
// balances are read from here, and the rules that protect it are enforced by
// the database rather than by whichever service happened to write last.
//
// What Postgres adds that SQLite cannot:
//
//   - 0018's append-only trigger. A row here cannot be edited or deleted by
//     anyone, including the table owner. A correction is a compensating entry.
//   - RLS. The app connects as nutriquest_app, so a query can only ever see
//     the player in app.current_player — a missing WHERE clause stops being a
//     data leak.
//   - app.wallets.balance >= 0, checked by the database on every write, so an
//     overdraft is impossible even if a caller forgets to check.
//
// Consistency model, stated plainly: a sale removes monsters from SQLite and
// credits coins here. Those are two stores, so there is no single transaction
// across them. The write is enqueued through the mirror outbox, which is
// durable and at-least-once, and every insert below is idempotent on the
// entry's own id — so the credit always lands exactly once, but it can land a
// moment after the monsters leave. That is the standard outbox trade, and it
// is why the entry id is generated by the caller rather than the database.
import { getPool, hasDatabaseUrl, withPlayer } from "../db/pg";
import { ensurePlayer } from "../db/repositories/players";
import type { CoinReason } from "./coins";

/** The currency name in app.currency_entries. Keys and capsules share the
 *  table; coins are one currency within it, added by migration 0012. */
const CURRENCY = "coins";

export interface CoinEntryPg {
  entryId: string;
  playerId: string;
  amount: number;
  reason: CoinReason;
  refId: string | null;
  createdAt: string;
}

/**
 * Authoritative balance: SUM over the ledger, not a stored column.
 *
 * Reads through the app pool rather than the replica: a balance is checked
 * immediately before a spend, and replica lag on that read would let a player
 * spend the same coins twice.
 */
export async function coinBalancePg(playerId: string): Promise<number> {
  const { rows } = await getPool().query(
    `select coalesce(sum(amount), 0)::bigint as balance
       from app.currency_entries
      where player_id = $1 and currency = $2`,
    [playerId, CURRENCY]
  );
  return Number(rows[0]?.balance ?? 0);
}

/**
 * Append one entry, authoritatively.
 *
 * Idempotent on `entryId`: the outbox delivers at least once, and a redelivery
 * must not credit twice. The balance check and the insert share one
 * transaction, so two concurrent spends cannot both pass the same check.
 *
 * The wallet row is kept in step in the same transaction. It is a cache of the
 * sum — `app.wallets.balance >= 0` is what turns "should not overdraft" into
 * "cannot", enforced by Postgres rather than by this function.
 */
export async function recordCoinsPg(
  playerId: string,
  entryId: string,
  amount: number,
  reason: CoinReason,
  refId: string | null = null
): Promise<void> {
  if (!Number.isInteger(amount) || amount === 0) {
    throw new Error("COIN_AMOUNT_INVALID");
  }

  await withPlayer(playerId, async (client) => {
    await ensurePlayer(client, playerId);

    // Already delivered? Then this is a retry and there is nothing to do.
    const seen = await client.query(
      `select 1 from app.currency_entries where operation_id = $1 limit 1`,
      [entryId]
    );
    if ((seen.rowCount ?? 0) > 0) return;

    if (amount < 0) {
      const { rows } = await client.query(
        `select coalesce(sum(amount), 0)::bigint as balance
           from app.currency_entries
          where player_id = $1 and currency = $2`,
        [playerId, CURRENCY]
      );
      if (Number(rows[0]?.balance ?? 0) + amount < 0) {
        throw new Error("INSUFFICIENT_COINS");
      }
    }

    await client.query(
      `insert into app.currency_entries
         (operation_id, entry_index, player_id, account, currency, amount, reason, ref)
       values ($1, 0, $2, 'player', $3, $4, $5, $6)
       on conflict (operation_id, entry_index) do nothing`,
      [entryId, playerId, CURRENCY, amount, reason, refId]
    );

    // The wallet is the balance the rest of the schema reads. Its CHECK is the
    // backstop that makes an overdraft impossible rather than merely refused.
    await client.query(
      `insert into app.wallets (player_id, currency, balance)
       values ($1, $2, $3)
       on conflict (player_id, currency) do update
         set balance    = app.wallets.balance + excluded.balance,
             updated_at = now(),
             version    = app.wallets.version + 1`,
      [playerId, CURRENCY, amount]
    );
  });
}

/** Ledger history straight from the authoritative store, newest first. */
export async function coinHistoryPg(playerId: string, limit = 50): Promise<CoinEntryPg[]> {
  const { rows } = await getPool().query(
    `select operation_id, player_id, amount, reason, ref, created_at
       from app.currency_entries
      where player_id = $1 and currency = $2
      order by created_at desc
      limit $3`,
    [playerId, CURRENCY, Math.min(Math.max(1, limit), 200)]
  );
  return rows.map((r) => ({
    entryId: String(r.operation_id),
    playerId: String(r.player_id),
    amount: Number(r.amount),
    reason: String(r.reason) as CoinReason,
    refId: r.ref === null || r.ref === undefined ? null : String(r.ref),
    createdAt:
      r.created_at instanceof Date ? r.created_at.toISOString() : String(r.created_at),
  }));
}

/** True when the authoritative store is reachable at all. */
export function coinsAreAuthoritativeInPg(): boolean {
  return hasDatabaseUrl();
}
